pipeline {
	agent any
		stages {

			stage('Encontrar Dockerfile, ejecutarlo') {
				steps {
					sh 'sudo su'
					sh 'sudo docker images'
					
				}
			} 

			stage('Three') {
				steps {sh 'echo "Step Three"'}
			}
		}
} 

 
